etudiant:
    pattern:  /etat_{status}
    defaults: { _controller: "BenLogementBundle:Person:index", status: all}

etudiant_elegible:
    pattern:  /elegible
    defaults: { _controller: "BenLogementBundle:Person:listElegible"}

etudiant_ajax:
    pattern:  /etudiants-list
    defaults: { _controller: BenLogementBundle:Person:ajaxList }
    requirements: { _method: post }

etudiant_show:
    pattern:  /{id}/show
    defaults: { _controller: "BenLogementBundle:Person:show" }

etudiant_new:
    pattern:  /new/{type}
    defaults: { _controller: "BenLogementBundle:Person:new" , type: nouveau}

etudiant_create:
    pattern:  /create
    defaults: { _controller: "BenLogementBundle:Person:create" }
    requirements: { _method: post }

etudiant_edit:
    pattern:  /{id}/edit/{type}
    defaults: { _controller: "BenLogementBundle:Person:edit" }

etudiant_update:
    pattern:  /{id}/update
    defaults: { _controller: "BenLogementBundle:Person:update" }
    requirements: { _method: post }

etudiant_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BenLogementBundle:Person:delete" }
    requirements: { _method: post }

etudiant_status:
    pattern:  /status/{status}
    defaults: { _controller: "BenLogementBundle:Person:setStatus"}
    requirements: { _method: post }

etudiant_cancel:
    pattern:  /cancel
    defaults: { _controller: "BenLogementBundle:Person:cancel"}
    requirements: { _method: post }

etudiant_generate_list:
    pattern:  /generate/list
    defaults: { _controller: BenLogementBundle:Person:generateList }
etudiant_validate_list:
    pattern:  /generate/list/valide
    defaults: { _controller: BenLogementBundle:Person:validateList }
    requirements: { _method: post }