parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     BenLogement
    database_user:     root
    database_password: ~

    sqlite_driver:     pdo_sqlite
    sqlite_path:       %kernel.root_dir%/../web/uploads/sqlite/sqlite.db
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            0d958s0f6assdda91f1d33f7f7dba8a6
    nombreParPage:     8
    adminPaginator:     3
    domaine_name:     benlogement.com
    nice_name:     benlogement
    webmaster:     no-replay@benlogement.com
    appfolder:     logement
    asset_url:     http://127.0.0.1/logement/web/

    person_foreign:   etranger
    person_new:       nouveau
    person_old:       ancien
    person_special:   special
    person_not_valide:   non valide
    person_valide:   valide
    person_eligible:   éligible
    person_resident:   résidant

