<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
	public function findbyLogement($logement) {     
       $qb = $this->createQueryBuilder('b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement)
                ;
        return $qb->getQuery()->getResult();
    }

    public function counter($logement) {
        $qb = $this->createQueryBuilder('b')
                ->select('COUNT(b)')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
