<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementRepository extends EntityRepository
{
}
