<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
   
	public function findbyLogement($logement, $perPage, $page, $status) {     
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.room', 'room')
                ->addSelect('room')
                ->leftJoin('r.person', 'p')
                ->addSelect('p')
                ->leftJoin('p.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement)
                ;

        if ($status !== 'all')
            $qb->andWhere('r.status = :status')
                ->setParameter('status', $status);
        $qb->setFirstResult(($page - 1) * $perPage)
        ->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }
}
