<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    public function findbyLogement($logement) {     
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.block', 'b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement)
                ;
        return $qb->getQuery()->getResult();
    }

    public function findRoombyName($logement, $block, $room) {     
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.block', 'b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('r.name like :room')
                ->setParameter('room', $room)
                ->andWhere('b.name like :block')
                ->setParameter('block', $block)
                ->andWhere('l.name like :logement')
                ->setParameter('logement', $logement)
                ;
        if ($qb->getQuery()->getResult()) {
           return $qb->getQuery()->getResult()[0];
        }
        return null;
        
    }

    public function search($perPage, $page, $logement, $searchEntity) {     
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.block', 'b')
                ->addSelect('b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement);

        if($searchEntity){
            if($searchEntity['block'] !== ''){
                if(0+$searchEntity['block'] === 0)
                    $qb->andWhere('b.name = :block')->setParameter('block', $searchEntity['block']);
                else
                    $qb->andWhere('b.id = :block')->setParameter('block', $searchEntity['block']);
            }
            if($searchEntity['gender'] !== '')
                $qb->andWhere('b.type = :gender')->setParameter('gender', $searchEntity['gender']);
            if($searchEntity['name'] !== '')
                $qb->andWhere('r.name = :name')->setParameter('name', $searchEntity['name']);
            if($searchEntity['floor'] !== '')
                $qb->andWhere('r.floor = :floor')->setParameter('floor', $searchEntity['floor']);
            if($searchEntity['capacity'] !== '')
                $qb->andWhere('r.capacity = :capacity')->setParameter('capacity', $searchEntity['capacity']);
            if($searchEntity['status'] === 'free')
                $qb->andWhere('r.free > 0');
            elseif($searchEntity['status'] === 'notfree')
                $qb->andWhere('r.free = 0');
        }


        $qb->setFirstResult(($page - 1) * $perPage)
        ->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }


    public function counter($logement, $status = 'all', $type = 'all') {
        $qb = $this->createQueryBuilder('r')
                ->select('COUNT(r)')
                ->leftJoin('r.block', 'b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement);
        if($status === 'free') 
            $qb->andWhere('r.free > 0');
        elseif ($status === 'notfree')
            $qb->andWhere('r.free > 0');

        if($type !== 'all') 
            $qb->andWhere('b.type = :type')
                ->setParameter('type', $type);

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function sum($logement, $status = 'all', $type = 'all') {
        $qb = $this->createQueryBuilder('r')
                ->select('SUM(r.capacity)')
                ->leftJoin('r.block', 'b')
                ->leftJoin('b.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement);
        if($status === 'free') 
            $qb->andWhere('r.free > 0');
        elseif ($status === 'notfree')
            $qb->andWhere('r.free > 0');

        if($type !== 'all') 
            $qb->andWhere('b.type = :type')
                ->setParameter('type', $type);

        return $qb->getQuery()->getSingleScalarResult();
    }


    public function getStats($logement) {
        $sql1 = "
        select * from 
            (select SUM(capacity) capacity from room left join block on block.id =room.block_id where block.logement_id = $logement) A
        join(select SUM(capacity) capacityMen from room left join block on block.id =room.block_id where block.type = 'Garçon' and block.logement_id = $logement) B
        join(select SUM(capacity) capacityWomen from room left join block on block.id =room.block_id where block.type = 'Fille' and block.logement_id = $logement) C
        join(select SUM(free) available from room left join block on block.id =room.block_id where block.logement_id = $logement) D
        join(select SUM(free) availableMen from room left join block on block.id =room.block_id where block.type = 'Garçon' and block.logement_id = $logement) E
        join(select SUM(free) availableWomen from room left join block on block.id =room.block_id where block.type = 'Fille' and block.logement_id = $logement) F;
        ";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql1);
        $stmt->execute();
        return  $stmt->fetchAll()[0];
    }
}
