<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends EntityRepository
{
	public function getEtablissement($id)
	{
		 $qb = $this->createQueryBuilder('u')
                ->leftJoin('u.parent', 'p')
                ->andWhere('p.id = :id')
                ->setParameter('id', $id)
		 		->getQuery();
		 
		 return $qb->getArrayResult();
	}
}
