<?php

namespace Ben\LogementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ben\LogementBundle\Entity\Person;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends EntityRepository
{
	public function getEtablissement($id)
	{
		 $qb = $this->createQueryBuilder('u')
                ->leftJoin('u.parent', 'p')
                ->andWhere('p.id = :id')
                ->setParameter('id', $id)
		 		->getQuery();
		 
		 return $qb->getArrayResult();
	}

	public function findUniversity($logement, $gender = null) {       
       $qb = $this->createQueryBuilder('u')
                ->select('distinct u.id, u.name')
                ->leftJoin('u.persons', 'p')
                ->leftJoin('p.logement', 'l')
                ->andWhere('l.id = :logement')
                ->setParameter('logement', $logement)
                ->andWhere('p.status = :status')
                ->setParameter('status', Person::$valideStatus)
                ->andWhere('p.type != :type')
                ->setParameter('type', Person::$oldType);
        if(isset($gender))
            $qb->andWhere('p.gender = :gender')->setParameter('gender', $gender);

       return $qb->getQuery()->getArrayResult();
    }
}
