<?php

namespace Ben\LogementBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PersonController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/wamp/www/logement/app/cache/dev/jms_diextra/proxies/Ben-LogementBundle-Controller-PersonController.php';
        $g = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\LogementBundle\\Controller\\PersonController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'listElegibleAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'setStatusAction' => array(0 => 'security.access.method_interceptor'), 'generateListAction' => array(0 => 'security.access.method_interceptor'), 'validateListAction' => array(0 => 'security.access.method_interceptor'), 'clearOrdersAction' => array(0 => 'security.access.method_interceptor'), 'removeSomeAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'cancelAction' => array(0 => 'security.access.method_interceptor'), 'toExcelAction' => array(0 => 'security.access.method_interceptor'), 'toPdfAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy480ea229_420f74158b596624dc39bc3f65860a7602d6ccb0\__CG__\Ben\LogementBundle\Controller\PersonController();
        $instance->__CGInterception__setLoader($g);
        return $instance;
    }
}
