<?php

namespace Ben\LogementBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/wamp/www/logement/app/cache/dev/jms_diextra/proxies/Ben-LogementBundle-Controller-DefaultController.php';
        $e = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\LogementBundle\\Controller\\DefaultController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'importAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy480ea229_edf5565f209d7d793a2e186c37daff062cdb8235\__CG__\Ben\LogementBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($e);
        return $instance;
    }
}
