<?php

namespace Ben\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ResettingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ben\UserBundle\Controller\ResettingController();
        return $instance;
    }
}
