<?php

namespace Ben\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/wamp/www/logement/app/cache/dev/jms_diextra/proxies/Ben-UserBundle-Controller-GroupController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\UserBundle\\Controller\\GroupController' => array('listAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy480ea229_209c1471bd4965eeea62c412a9a107b728cb3fa9\__CG__\Ben\UserBundle\Controller\GroupController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
