<?php

namespace Proxies\__CG__\Ben\LogementBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Reservation extends \Ben\LogementBundle\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDatePayement($datePayement)
    {
        $this->__load();
        return parent::setDatePayement($datePayement);
    }

    public function getDatePayement()
    {
        $this->__load();
        return parent::getDatePayement();
    }

    public function setDateFrom($dateFrom)
    {
        $this->__load();
        return parent::setDateFrom($dateFrom);
    }

    public function getDateFrom()
    {
        $this->__load();
        return parent::getDateFrom();
    }

    public function setDateTo($dateTo)
    {
        $this->__load();
        return parent::setDateTo($dateTo);
    }

    public function getDateTo()
    {
        $this->__load();
        return parent::getDateTo();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function isValide()
    {
        $this->__load();
        return parent::isValide();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setPerson(\Ben\LogementBundle\Entity\Person $person)
    {
        $this->__load();
        return parent::setPerson($person);
    }

    public function getPerson()
    {
        $this->__load();
        return parent::getPerson();
    }

    public function setRoom(\Ben\LogementBundle\Entity\Room $room)
    {
        $this->__load();
        return parent::setRoom($room);
    }

    public function getRoom()
    {
        $this->__load();
        return parent::getRoom();
    }

    public function setOldroom($oldroom)
    {
        $this->__load();
        return parent::setOldroom($oldroom);
    }

    public function getOldroom()
    {
        $this->__load();
        return parent::getOldroom();
    }

    public function switchRoom(\Ben\LogementBundle\Entity\Reservation $entity)
    {
        $this->__load();
        return parent::switchRoom($entity);
    }

    public function freeRoom()
    {
        $this->__load();
        return parent::freeRoom();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date_payement', 'date_from', 'date_to', 'status', 'price', 'person', 'room');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}