<?php

namespace Proxies\__CG__\Ben\LogementBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Room extends \Ben\LogementBundle\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setFloor($floor)
    {
        $this->__load();
        return parent::setFloor($floor);
    }

    public function getFloor()
    {
        $this->__load();
        return parent::getFloor();
    }

    public function setCapacity($capacity)
    {
        $this->__load();
        return parent::setCapacity($capacity);
    }

    public function getCapacity()
    {
        $this->__load();
        return parent::getCapacity();
    }

    public function plusFree()
    {
        $this->__load();
        return parent::plusFree();
    }

    public function minusFree()
    {
        $this->__load();
        return parent::minusFree();
    }

    public function setFree($free)
    {
        $this->__load();
        return parent::setFree($free);
    }

    public function getFree()
    {
        $this->__load();
        return parent::getFree();
    }

    public function isFree()
    {
        $this->__load();
        return parent::isFree();
    }

    public function setBlock(\Ben\LogementBundle\Entity\Block $block)
    {
        $this->__load();
        return parent::setBlock($block);
    }

    public function getBlock()
    {
        $this->__load();
        return parent::getBlock();
    }

    public function addReservation(\Ben\LogementBundle\Entity\Reservation $reservation)
    {
        $this->__load();
        return parent::addReservation($reservation);
    }

    public function removeReservation(\Ben\LogementBundle\Entity\Reservation $reservation)
    {
        $this->__load();
        return parent::removeReservation($reservation);
    }

    public function getReservations()
    {
        $this->__load();
        return parent::getReservations();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'floor', 'capacity', 'free', 'block', 'reservations');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}