<?php

namespace Proxies\__CG__\Ben\LogementBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Logement extends \Ben\LogementBundle\Entity\Logement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setPlaceEtranger($placeEtranger)
    {
        $this->__load();
        return parent::setPlaceEtranger($placeEtranger);
    }

    public function getPlaceEtranger()
    {
        $this->__load();
        return parent::getPlaceEtranger();
    }

    public function setPlaceAncien($placeAncien)
    {
        $this->__load();
        return parent::setPlaceAncien($placeAncien);
    }

    public function getPlaceAncien()
    {
        $this->__load();
        return parent::getPlaceAncien();
    }

    public function getBlocks()
    {
        $this->__load();
        return parent::getBlocks();
    }

    public function getOrderlists()
    {
        $this->__load();
        return parent::getOrderlists();
    }

    public function getPersons()
    {
        $this->__load();
        return parent::getPersons();
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'city', 'place_etranger', 'place_ancien', 'blocks', 'persons', 'users', 'orderlists');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}